# Generated by Django 2.0.2 on 2018-11-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='comments',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
