# Generated by Django 2.0.2 on 2021-01-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0003_auto_20200905_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='author',
            field=models.TextField(db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='puzzleType',
            field=models.TextField(db_index=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='title',
            field=models.TextField(db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='topics',
            field=models.TextField(db_index=True, default='', max_length=200),
        ),
    ]
