# Generated by Django 2.0.2 on 2019-05-31 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codejam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundresult',
            name='round',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='codejam.Round'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roundresult',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='codejam.User'),
            preserve_default=False,
        ),
    ]
