# Generated by Django 2.0.2 on 2019-05-31 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codejam', '0002_auto_20190531_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='codejam.Country'),
            preserve_default=False,
        ),
    ]
