# Generated by Django 2.0.2 on 2019-06-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codejam', '0004_roundresult_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundresult',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
