# Generated by Django 2.0.2 on 2019-06-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codejam', '0005_roundresult_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roundresult',
            name='order',
        ),
        migrations.AddField(
            model_name='round',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
