# Generated by Django 2.0.2 on 2021-09-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.TextField()),
                ('botReplays', models.TextField()),
                ('replayGroups', models.TextField()),
            ],
        ),
    ]
